import { GIFT_CARD_MAX_VALUE_MINOR_UNITS } from "@mocha-house/contracts";
import type {
  AdjustGiftCardBalanceRequest,
  IssueGiftCardRequest,
  UpdateGiftCardConfigurationRequest,
} from "@mocha-house/contracts";
import { parseDollarInput } from "@/lib/money";

// The ONE place the HQ gift-card forms' client-side validation and request
// shaping live (Milestone 7F). The API
// (`/api/v1/admin/gift-cards*`, CORPORATE-only) re-validates everything —
// these helpers just keep the forms honest before they submit.

export const GIFT_CARD_REASON_MAX_LENGTH = 1000;

export type CorrectionDirection = "add" | "deduct";

export type PrepareResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: string };

// --- Issue -----------------------------------------------------------

export function prepareIssue(amountInput: string): PrepareResult<IssueGiftCardRequest> {
  const parsed = parseDollarInput(amountInput);
  if (!parsed.ok) {
    return { ok: false, error: parsed.error };
  }
  if (parsed.cents === null || parsed.cents <= 0) {
    return { ok: false, error: "Enter a gift-card amount greater than $0.00." };
  }
  if (parsed.cents > GIFT_CARD_MAX_VALUE_MINOR_UNITS) {
    return {
      ok: false,
      error: "A gift card cannot be worth more than $2,000.00.",
    };
  }
  return { ok: true, value: { originalValueMinorUnits: parsed.cents } };
}

// --- Manual balance correction ------------------------------------

export interface CorrectionFormValues {
  direction: CorrectionDirection;
  amount: string; // raw dollar text
  reason: string;
}

// `operationKey` is generated by the caller (a UUID) and REUSED across a
// retry of the same submission so a lost-response retry is idempotent.
export function prepareCorrection(
  values: CorrectionFormValues,
  operationKey: string,
): PrepareResult<AdjustGiftCardBalanceRequest> {
  const parsed = parseDollarInput(values.amount);
  if (!parsed.ok) {
    return { ok: false, error: parsed.error };
  }
  if (parsed.cents === null || parsed.cents <= 0) {
    return { ok: false, error: "Enter an amount greater than $0.00." };
  }
  if (parsed.cents > GIFT_CARD_MAX_VALUE_MINOR_UNITS) {
    return { ok: false, error: "That amount is above the $2,000.00 ceiling." };
  }

  const reason = values.reason.trim();
  if (reason.length === 0) {
    return { ok: false, error: "A reason is required." };
  }
  if (reason.length > GIFT_CARD_REASON_MAX_LENGTH) {
    return {
      ok: false,
      error: `Keep the reason under ${GIFT_CARD_REASON_MAX_LENGTH} characters.`,
    };
  }

  const deltaMinorUnits =
    values.direction === "deduct" ? -parsed.cents : parsed.cents;

  return { ok: true, value: { deltaMinorUnits, reason, operationKey } };
}

// Would this correction take the balance outside [0, $2,000.00]? The API
// enforces this authoritatively; the form uses it to warn before submitting.
export function correctionWouldBeOutOfRange(
  currentBalanceMinorUnits: number,
  deltaMinorUnits: number,
): boolean {
  const next = currentBalanceMinorUnits + deltaMinorUnits;
  return next < 0 || next > GIFT_CARD_MAX_VALUE_MINOR_UNITS;
}

// --- Configuration ----------------------------------------------

export interface ConfigurationFormValues {
  // One dollar amount per line / entry.
  presetInputs: string[];
  customAmountEnabled: boolean;
}

export function prepareConfiguration(
  values: ConfigurationFormValues,
): PrepareResult<UpdateGiftCardConfigurationRequest> {
  const cleaned = values.presetInputs
    .map((raw) => raw.trim())
    .filter((raw) => raw.length > 0);

  if (cleaned.length === 0) {
    return { ok: false, error: "Add at least one preset amount." };
  }
  if (cleaned.length > 12) {
    return { ok: false, error: "Add at most 12 preset amounts." };
  }

  const seen = new Set<number>();
  for (const raw of cleaned) {
    const parsed = parseDollarInput(raw);
    if (!parsed.ok || parsed.cents === null || parsed.cents <= 0) {
      return { ok: false, error: `"${raw}" is not a valid amount.` };
    }
    if (parsed.cents > GIFT_CARD_MAX_VALUE_MINOR_UNITS) {
      return {
        ok: false,
        error: `"${raw}" is above the $2,000.00 ceiling.`,
      };
    }
    if (seen.has(parsed.cents)) {
      return { ok: false, error: `"${raw}" is listed more than once.` };
    }
    seen.add(parsed.cents);
  }

  return {
    ok: true,
    value: {
      presetAmountsMinorUnits: [...seen].sort((a, b) => a - b),
      customAmountEnabled: values.customAmountEnabled,
    },
  };
}

// A normalized lookup query for the "find a gift card" form.
export function normalizeGiftCardQuery(raw: string): string {
  return raw.trim();
}
