import type { Prisma } from '../generated/prisma/client';

// Security 4C-1 — every reference from one business-owned record to
// another, classified by how the database can (later) enforce that both
// sides belong to the same business. The tenant relationship inventory
// spec (apps/api/src/tenancy/tenant-relationship-inventory.spec.ts)
// re-derives this list from schema.prisma and fails when a relationship
// appears, disappears or changes without being classified here.
//
//   composite-fk-candidate — a real reference to one parent table. Either
//       an existing single-column foreign key (hasForeignKey: true), or a
//       plain column that should get one (hasForeignKey: false). Target of
//       Security 4C-2+: FOREIGN KEY ("tenantId", col) -> parent("tenantId", id).
//   historical-snapshot — an id copied by value into a completed record;
//       deliberately never joined, may outlive its source.
//   polymorphic — an id whose target table depends on a type column.
//   json-reference — ids inside a JSON document. `paths` lists the ones
//       that point at live business records; an empty list documents a
//       JSON field that carries only snapshot data.
//   external-identifier — an id issued by an outside system.
//
// Nothing here is an authorization check: runtime ownership checks remain
// the enforcement. The inventory drives the read-only integrity checker
// (tenant-integrity-checker.ts) and the 4C-2+ migration plan.

export type TenantOwnedModel = Exclude<Prisma.ModelName, 'Tenant'>;

export type ReferentialAction = 'Cascade' | 'Restrict' | 'SetNull' | 'NoAction';

export type RelationshipKind =
  | 'composite-fk-candidate'
  | 'historical-snapshot'
  | 'polymorphic'
  | 'json-reference'
  | 'external-identifier';

interface RelationshipBase {
  // `${model}.${column}` — unique.
  readonly id: string;
  readonly model: TenantOwnedModel;
  readonly column: string;
  readonly nullable: boolean;
  readonly note?: string;
}

export interface DirectReference extends RelationshipBase {
  readonly kind: 'composite-fk-candidate' | 'historical-snapshot';
  readonly target: TenantOwnedModel;
  readonly hasForeignKey: boolean;
  // The effective ON DELETE action of the existing foreign key.
  readonly onDelete?: ReferentialAction;
  // Security 4C-3+ — the foreign key is composite, ("tenantId", column) ->
  // target ("tenantId", "id"), so PostgreSQL itself rejects a reference to
  // another business's row.
  readonly tenantEnforced?: boolean;
}

export interface PolymorphicReference extends RelationshipBase {
  readonly kind: 'polymorphic';
  readonly typeColumn: string;
  // Type value -> target table, for types whose id is a record id.
  readonly targets: Readonly<Record<string, TenantOwnedModel>>;
  // Type value -> a per-business key the id holds instead of a record id
  // (e.g. a notification purpose). Checked like a record reference.
  readonly keyedTargets?: Readonly<
    Record<
      string,
      { readonly model: TenantOwnedModel; readonly column: string }
    >
  >;
  // Type value -> the only id it may carry (e.g. 'company' for a
  // business-wide configuration). Any other id is invalid.
  readonly fixedTargets?: Readonly<Record<string, string>>;
  // Type values for which the id must be NULL / must be set.
  readonly nullForTypes?: readonly string[];
  readonly requiredForTypes?: readonly string[];
  // A target that no longer exists: a violation for live data (an
  // authorization scope), a warning for history (an audit entry).
  readonly missingTarget: 'violation' | 'warning';
  // Rows still being acted on (e.g. a PENDING outbox event): for these a
  // missing target is always a violation, whatever `missingTarget` says.
  readonly activeWhen?: {
    readonly column: string;
    readonly values: readonly string[];
  };
}

export interface JsonReference extends RelationshipBase {
  readonly kind: 'json-reference';
  readonly paths: ReadonlyArray<{
    readonly path: readonly string[];
    readonly target: TenantOwnedModel;
  }>;
}

export interface ExternalIdentifier extends RelationshipBase {
  readonly kind: 'external-identifier';
  readonly system: string;
}

export type TenantRelationship =
  DirectReference | PolymorphicReference | JsonReference | ExternalIdentifier;

// Primary-key columns of every business-owned table (used only to report
// WHICH rows violate, by key — never their contents).
export const TENANT_MODEL_KEYS: Readonly<
  Record<TenantOwnedModel, readonly string[]>
> = Object.freeze({
  ApprovalRequest: ['id'],
  Campaign: ['id'],
  CampaignProduct: ['campaignId', 'productId'],
  Category: ['id'],
  ChecklistInstance: ['id'],
  ChecklistInstanceItem: ['id'],
  ChecklistTemplate: ['id'],
  ChecklistTemplateItem: ['id'],
  CmsPage: ['id'],
  Customer: ['id'],
  CustomerLoyaltyAccount: ['id'],
  CustomerNote: ['id'],
  CustomerPreferredLocation: ['id'],
  FranchiseInquiry: ['id'],
  FranchiseInquiryNote: ['id'],
  GiftCard: ['id'],
  GiftCardConfiguration: ['id'],
  GiftCardPurchase: ['id'],
  GiftCardTransaction: ['id'],
  InternalAuditEvent: ['id'],
  InternalRole: ['id'],
  InternalRolePermission: ['roleId', 'permissionKey'],
  InternalUser: ['id'],
  InternalUserRoleAssignment: ['id'],
  JobApplication: ['id'],
  JobApplicationNote: ['id'],
  JobOpening: ['id'],
  Location: ['id'],
  LocationMenu: ['locationId', 'menuId'],
  LocationProductAvailabilityOverride: ['locationId', 'menuId', 'productId'],
  LocationProductPriceOverride: ['locationId', 'menuId', 'productId'],
  LoyaltyBonusPromotion: ['id'],
  LoyaltyBonusPromotionLocation: ['promotionId', 'locationId'],
  LoyaltyBonusPromotionProduct: ['promotionId', 'productId'],
  LoyaltyConfiguration: ['id'],
  LoyaltyReward: ['id'],
  LoyaltyRewardCategory: ['rewardId', 'categoryId'],
  LoyaltyRewardProduct: ['rewardId', 'productId'],
  MediaAsset: ['id'],
  Menu: ['id'],
  MenuProduct: ['menuId', 'productId'],
  MochaBeanLedgerEntry: ['id'],
  ModifierGroup: ['id'],
  ModifierOption: ['id'],
  NotificationDelivery: ['id'],
  NotificationRecipient: ['id'],
  OperationsTask: ['id'],
  Order: ['id'],
  OrderGiftCardRedemption: ['id'],
  OrderLine: ['id'],
  OrderLoyaltyBonus: ['id'],
  OrderLoyaltyBonusItem: ['id'],
  OrderLoyaltyRewardRedemption: ['id'],
  OrderPromotionRedemption: ['id'],
  OrderStatusHistory: ['id'],
  OutboxEvent: ['id'],
  PaymentAttempt: ['id'],
  Product: ['id'],
  ProductModifierGroup: ['productId', 'modifierGroupId'],
  Promotion: ['id'],
  PromotionCategory: ['promotionId', 'categoryId'],
  PromotionCustomerUsage: ['promotionId', 'customerId'],
  PromotionLocation: ['promotionId', 'locationId'],
  PromotionProduct: ['promotionId', 'productId'],
});

const DIRECT_REFERENCES: readonly DirectReference[] = [
  {
    id: 'Product.categoryId',
    kind: 'composite-fk-candidate',
    model: 'Product',
    column: 'categoryId',
    target: 'Category',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ModifierOption.modifierGroupId',
    kind: 'composite-fk-candidate',
    model: 'ModifierOption',
    column: 'modifierGroupId',
    target: 'ModifierGroup',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ProductModifierGroup.productId',
    kind: 'composite-fk-candidate',
    model: 'ProductModifierGroup',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ProductModifierGroup.modifierGroupId',
    kind: 'composite-fk-candidate',
    model: 'ProductModifierGroup',
    column: 'modifierGroupId',
    target: 'ModifierGroup',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'MenuProduct.menuId',
    kind: 'composite-fk-candidate',
    model: 'MenuProduct',
    column: 'menuId',
    target: 'Menu',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'MenuProduct.productId',
    kind: 'composite-fk-candidate',
    model: 'MenuProduct',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationMenu.locationId',
    kind: 'composite-fk-candidate',
    model: 'LocationMenu',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationMenu.menuId',
    kind: 'composite-fk-candidate',
    model: 'LocationMenu',
    column: 'menuId',
    target: 'Menu',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductPriceOverride.locationId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductPriceOverride',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductPriceOverride.menuId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductPriceOverride',
    column: 'menuId',
    target: 'Menu',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductPriceOverride.productId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductPriceOverride',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductAvailabilityOverride.locationId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductAvailabilityOverride',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductAvailabilityOverride.menuId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductAvailabilityOverride',
    column: 'menuId',
    target: 'Menu',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LocationProductAvailabilityOverride.productId',
    kind: 'composite-fk-candidate',
    model: 'LocationProductAvailabilityOverride',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'CustomerPreferredLocation.customerId',
    kind: 'composite-fk-candidate',
    model: 'CustomerPreferredLocation',
    column: 'customerId',
    target: 'Customer',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
    tenantEnforced: true,
  },
  {
    id: 'CustomerPreferredLocation.locationId',
    kind: 'composite-fk-candidate',
    model: 'CustomerPreferredLocation',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
    tenantEnforced: true,
  },
  {
    id: 'Order.locationId',
    kind: 'composite-fk-candidate',
    model: 'Order',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
    tenantEnforced: true,
  },
  {
    id: 'Order.customerId',
    kind: 'composite-fk-candidate',
    model: 'Order',
    column: 'customerId',
    target: 'Customer',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'SetNull',
    tenantEnforced: true,
  },
  {
    id: 'Order.paymentAttemptId',
    kind: 'composite-fk-candidate',
    model: 'Order',
    column: 'paymentAttemptId',
    target: 'PaymentAttempt',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
    tenantEnforced: true,
  },
  {
    id: 'OrderLine.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderLine',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
    tenantEnforced: true,
  },
  {
    id: 'OrderStatusHistory.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderStatusHistory',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
    tenantEnforced: true,
  },
  {
    id: 'NotificationDelivery.outboxEventId',
    kind: 'composite-fk-candidate',
    model: 'NotificationDelivery',
    column: 'outboxEventId',
    target: 'OutboxEvent',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'InternalAuditEvent.actorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'InternalAuditEvent',
    column: 'actorInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'InternalRolePermission.roleId',
    kind: 'composite-fk-candidate',
    model: 'InternalRolePermission',
    column: 'roleId',
    target: 'InternalRole',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'InternalUserRoleAssignment.internalUserId',
    kind: 'composite-fk-candidate',
    model: 'InternalUserRoleAssignment',
    column: 'internalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'InternalUserRoleAssignment.roleId',
    kind: 'composite-fk-candidate',
    model: 'InternalUserRoleAssignment',
    column: 'roleId',
    target: 'InternalRole',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ChecklistTemplateItem.templateId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistTemplateItem',
    column: 'templateId',
    target: 'ChecklistTemplate',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'ChecklistInstance.templateId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistInstance',
    column: 'templateId',
    target: 'ChecklistTemplate',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ChecklistInstance.locationId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistInstance',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ChecklistInstanceItem.checklistInstanceId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistInstanceItem',
    column: 'checklistInstanceId',
    target: 'ChecklistInstance',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'ChecklistInstanceItem.completedByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistInstanceItem',
    column: 'completedByInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ChecklistInstanceItem.exceptionByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'ChecklistInstanceItem',
    column: 'exceptionByInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OperationsTask.locationId',
    kind: 'composite-fk-candidate',
    model: 'OperationsTask',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OperationsTask.createdByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'OperationsTask',
    column: 'createdByInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OperationsTask.completedByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'OperationsTask',
    column: 'completedByInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'CustomerLoyaltyAccount.customerId',
    kind: 'composite-fk-candidate',
    model: 'CustomerLoyaltyAccount',
    column: 'customerId',
    target: 'Customer',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'MochaBeanLedgerEntry.loyaltyAccountId',
    kind: 'composite-fk-candidate',
    model: 'MochaBeanLedgerEntry',
    column: 'loyaltyAccountId',
    target: 'CustomerLoyaltyAccount',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'MochaBeanLedgerEntry.orderId',
    kind: 'composite-fk-candidate',
    model: 'MochaBeanLedgerEntry',
    column: 'orderId',
    target: 'Order',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'SetNull',
  },
  {
    id: 'MochaBeanLedgerEntry.actorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'MochaBeanLedgerEntry',
    column: 'actorInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LoyaltyRewardProduct.rewardId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyRewardProduct',
    column: 'rewardId',
    target: 'LoyaltyReward',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'LoyaltyRewardProduct.productId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyRewardProduct',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LoyaltyRewardCategory.rewardId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyRewardCategory',
    column: 'rewardId',
    target: 'LoyaltyReward',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'LoyaltyRewardCategory.categoryId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyRewardCategory',
    column: 'categoryId',
    target: 'Category',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OrderLoyaltyRewardRedemption.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderLoyaltyRewardRedemption',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LoyaltyBonusPromotionProduct.promotionId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyBonusPromotionProduct',
    column: 'promotionId',
    target: 'LoyaltyBonusPromotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'LoyaltyBonusPromotionProduct.productId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyBonusPromotionProduct',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'LoyaltyBonusPromotionLocation.promotionId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyBonusPromotionLocation',
    column: 'promotionId',
    target: 'LoyaltyBonusPromotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'LoyaltyBonusPromotionLocation.locationId',
    kind: 'composite-fk-candidate',
    model: 'LoyaltyBonusPromotionLocation',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OrderLoyaltyBonus.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderLoyaltyBonus',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'OrderLoyaltyBonusItem.orderLoyaltyBonusId',
    kind: 'composite-fk-candidate',
    model: 'OrderLoyaltyBonusItem',
    column: 'orderLoyaltyBonusId',
    target: 'OrderLoyaltyBonus',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'PromotionProduct.promotionId',
    kind: 'composite-fk-candidate',
    model: 'PromotionProduct',
    column: 'promotionId',
    target: 'Promotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'PromotionProduct.productId',
    kind: 'composite-fk-candidate',
    model: 'PromotionProduct',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'PromotionCategory.promotionId',
    kind: 'composite-fk-candidate',
    model: 'PromotionCategory',
    column: 'promotionId',
    target: 'Promotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'PromotionCategory.categoryId',
    kind: 'composite-fk-candidate',
    model: 'PromotionCategory',
    column: 'categoryId',
    target: 'Category',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'PromotionLocation.promotionId',
    kind: 'composite-fk-candidate',
    model: 'PromotionLocation',
    column: 'promotionId',
    target: 'Promotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'PromotionLocation.locationId',
    kind: 'composite-fk-candidate',
    model: 'PromotionLocation',
    column: 'locationId',
    target: 'Location',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'PromotionCustomerUsage.promotionId',
    kind: 'composite-fk-candidate',
    model: 'PromotionCustomerUsage',
    column: 'promotionId',
    target: 'Promotion',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'PromotionCustomerUsage.customerId',
    kind: 'composite-fk-candidate',
    model: 'PromotionCustomerUsage',
    column: 'customerId',
    target: 'Customer',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'OrderPromotionRedemption.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderPromotionRedemption',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardTransaction.giftCardId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardTransaction',
    column: 'giftCardId',
    target: 'GiftCard',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardTransaction.actorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardTransaction',
    column: 'actorInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardTransaction.orderId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardTransaction',
    column: 'orderId',
    target: 'Order',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'SetNull',
  },
  {
    id: 'GiftCardTransaction.giftCardPurchaseId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardTransaction',
    column: 'giftCardPurchaseId',
    target: 'GiftCardPurchase',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'SetNull',
  },
  {
    id: 'OrderGiftCardRedemption.orderId',
    kind: 'composite-fk-candidate',
    model: 'OrderGiftCardRedemption',
    column: 'orderId',
    target: 'Order',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardPurchase.paymentAttemptId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardPurchase',
    column: 'paymentAttemptId',
    target: 'PaymentAttempt',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardPurchase.giftCardId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardPurchase',
    column: 'giftCardId',
    target: 'GiftCard',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'GiftCardPurchase.customerId',
    kind: 'composite-fk-candidate',
    model: 'GiftCardPurchase',
    column: 'customerId',
    target: 'Customer',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'SetNull',
  },
  {
    id: 'JobOpening.locationId',
    kind: 'composite-fk-candidate',
    model: 'JobOpening',
    column: 'locationId',
    target: 'Location',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'JobApplication.jobOpeningId',
    kind: 'composite-fk-candidate',
    model: 'JobApplication',
    column: 'jobOpeningId',
    target: 'JobOpening',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'JobApplicationNote.jobApplicationId',
    kind: 'composite-fk-candidate',
    model: 'JobApplicationNote',
    column: 'jobApplicationId',
    target: 'JobApplication',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'JobApplicationNote.authorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'JobApplicationNote',
    column: 'authorInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'CustomerNote.customerId',
    kind: 'composite-fk-candidate',
    model: 'CustomerNote',
    column: 'customerId',
    target: 'Customer',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
    tenantEnforced: true,
  },
  {
    id: 'CustomerNote.authorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'CustomerNote',
    column: 'authorInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'FranchiseInquiryNote.franchiseInquiryId',
    kind: 'composite-fk-candidate',
    model: 'FranchiseInquiryNote',
    column: 'franchiseInquiryId',
    target: 'FranchiseInquiry',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'FranchiseInquiryNote.authorInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'FranchiseInquiryNote',
    column: 'authorInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'MediaAsset.uploadedByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'MediaAsset',
    column: 'uploadedByInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'Campaign.promotionId',
    kind: 'composite-fk-candidate',
    model: 'Campaign',
    column: 'promotionId',
    target: 'Promotion',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'Campaign.loyaltyBonusPromotionId',
    kind: 'composite-fk-candidate',
    model: 'Campaign',
    column: 'loyaltyBonusPromotionId',
    target: 'LoyaltyBonusPromotion',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'CampaignProduct.campaignId',
    kind: 'composite-fk-candidate',
    model: 'CampaignProduct',
    column: 'campaignId',
    target: 'Campaign',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Cascade',
  },
  {
    id: 'CampaignProduct.productId',
    kind: 'composite-fk-candidate',
    model: 'CampaignProduct',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ApprovalRequest.requestedByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'ApprovalRequest',
    column: 'requestedByInternalUserId',
    target: 'InternalUser',
    nullable: false,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'ApprovalRequest.decidedByInternalUserId',
    kind: 'composite-fk-candidate',
    model: 'ApprovalRequest',
    column: 'decidedByInternalUserId',
    target: 'InternalUser',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
  },
  {
    id: 'PaymentAttempt.locationId',
    kind: 'composite-fk-candidate',
    model: 'PaymentAttempt',
    column: 'locationId',
    target: 'Location',
    nullable: true,
    hasForeignKey: true,
    onDelete: 'Restrict',
    note: 'Food-order checkout sets it; a gift-card purchase leaves it null. Composite foreign key since Security 4C-3.',
    tenantEnforced: true,
  },
  {
    id: 'OrderPromotionRedemption.customerId',
    kind: 'composite-fk-candidate',
    model: 'OrderPromotionRedemption',
    column: 'customerId',
    target: 'Customer',
    nullable: true,
    hasForeignKey: false,
    note: 'The customer a per-customer promotion limit counts against. No foreign key yet.',
  },
  {
    id: 'Campaign.mediaAssetId',
    kind: 'composite-fk-candidate',
    model: 'Campaign',
    column: 'mediaAssetId',
    target: 'MediaAsset',
    nullable: true,
    hasForeignKey: false,
    note: 'Plain media reference (see media-reference-check.ts). No foreign key yet.',
  },
  {
    id: 'OrderLine.productId',
    kind: 'historical-snapshot',
    model: 'OrderLine',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderLoyaltyRewardRedemption.sourceRewardId',
    kind: 'historical-snapshot',
    model: 'OrderLoyaltyRewardRedemption',
    column: 'sourceRewardId',
    target: 'LoyaltyReward',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderLoyaltyRewardRedemption.freeItemProductId',
    kind: 'historical-snapshot',
    model: 'OrderLoyaltyRewardRedemption',
    column: 'freeItemProductId',
    target: 'Product',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderLoyaltyBonusItem.sourcePromotionId',
    kind: 'historical-snapshot',
    model: 'OrderLoyaltyBonusItem',
    column: 'sourcePromotionId',
    target: 'LoyaltyBonusPromotion',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderLoyaltyBonusItem.productId',
    kind: 'historical-snapshot',
    model: 'OrderLoyaltyBonusItem',
    column: 'productId',
    target: 'Product',
    nullable: false,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderPromotionRedemption.sourcePromotionId',
    kind: 'historical-snapshot',
    model: 'OrderPromotionRedemption',
    column: 'sourcePromotionId',
    target: 'Promotion',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderPromotionRedemption.freeItemProductId',
    kind: 'historical-snapshot',
    model: 'OrderPromotionRedemption',
    column: 'freeItemProductId',
    target: 'Product',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
  {
    id: 'OrderGiftCardRedemption.sourceGiftCardId',
    kind: 'historical-snapshot',
    model: 'OrderGiftCardRedemption',
    column: 'sourceGiftCardId',
    target: 'GiftCard',
    nullable: true,
    hasForeignKey: false,
    note: 'Snapshot by value; kept only to point at its source and never trusted for display or accounting.',
  },
];

const AUDIT_TARGETS = {
  approval_request: 'ApprovalRequest',
  campaign: 'Campaign',
  checklist_instance_item: 'ChecklistInstanceItem',
  cms_page: 'CmsPage',
  customer: 'Customer',
  franchise_inquiry: 'FranchiseInquiry',
  gift_card: 'GiftCard',
  internal_user: 'InternalUser',
  job_application: 'JobApplication',
  job_opening: 'JobOpening',
  loyalty_bonus_promotion: 'LoyaltyBonusPromotion',
  loyalty_reward: 'LoyaltyReward',
  media_asset: 'MediaAsset',
  promotion: 'Promotion',
} as const satisfies Record<string, TenantOwnedModel>;

const OUTBOX_AGGREGATES = {
  Order: 'Order',
  JobApplication: 'JobApplication',
  FranchiseInquiry: 'FranchiseInquiry',
} as const satisfies Record<string, TenantOwnedModel>;

const POLYMORPHIC_REFERENCES: readonly PolymorphicReference[] = [
  {
    id: 'InternalUserRoleAssignment.scopeId',
    kind: 'polymorphic',
    model: 'InternalUserRoleAssignment',
    column: 'scopeId',
    nullable: true,
    typeColumn: 'scopeType',
    targets: { LOCATION: 'Location' },
    nullForTypes: ['CORPORATE'],
    requiredForTypes: ['LOCATION'],
    missingTarget: 'violation',
    note: 'Staff authorization scope: CORPORATE has no scope id; LOCATION names a Location.',
  },
  {
    id: 'InternalAuditEvent.targetId',
    kind: 'polymorphic',
    model: 'InternalAuditEvent',
    column: 'targetId',
    nullable: false,
    typeColumn: 'targetType',
    targets: AUDIT_TARGETS,
    // Configuration audits name the whole business ('company'); recipient
    // audits name a notification purpose of that business.
    fixedTargets: {
      giftcard_configuration: 'company',
      loyalty_configuration: 'company',
    },
    keyedTargets: {
      notification_recipient: {
        model: 'NotificationRecipient',
        column: 'purpose',
      },
    },
    missingTarget: 'warning',
  },
  {
    id: 'ApprovalRequest.targetId',
    kind: 'polymorphic',
    model: 'ApprovalRequest',
    column: 'targetId',
    nullable: false,
    typeColumn: 'targetType',
    targets: { Campaign: 'Campaign' },
    missingTarget: 'violation',
  },
  {
    id: 'OutboxEvent.aggregateId',
    kind: 'polymorphic',
    model: 'OutboxEvent',
    column: 'aggregateId',
    nullable: false,
    typeColumn: 'aggregateType',
    targets: OUTBOX_AGGREGATES,
    // Processed / sent / failed rows are history; a PENDING row is still
    // going to be acted on, so its target must exist.
    missingTarget: 'warning',
    activeWhen: { column: 'status', values: ['PENDING'] },
  },
  {
    id: 'NotificationDelivery.aggregateId',
    kind: 'polymorphic',
    model: 'NotificationDelivery',
    column: 'aggregateId',
    nullable: false,
    typeColumn: 'aggregateType',
    targets: OUTBOX_AGGREGATES,
    // Processed / sent / failed rows are history; a PENDING row is still
    // going to be acted on, so its target must exist.
    missingTarget: 'warning',
    activeWhen: { column: 'status', values: ['PENDING'] },
  },
];

const JSON_REFERENCES: readonly JsonReference[] = [
  {
    id: 'CmsPage.draftContent',
    kind: 'json-reference',
    model: 'CmsPage',
    column: 'draftContent',
    nullable: false,
    paths: [{ path: ['hero', 'backgroundImageId'], target: 'MediaAsset' }],
    note: 'Home hero image (see media-reference-check.ts).',
  },
  {
    id: 'CmsPage.publishedContent',
    kind: 'json-reference',
    model: 'CmsPage',
    column: 'publishedContent',
    nullable: true,
    paths: [{ path: ['hero', 'backgroundImageId'], target: 'MediaAsset' }],
    note: 'Home hero image (see media-reference-check.ts).',
  },
  {
    id: 'OrderLine.selections',
    kind: 'json-reference',
    model: 'OrderLine',
    column: 'selections',
    nullable: false,
    paths: [],
    note: 'Modifier snapshot copied by value at checkout; never joined.',
  },
  {
    id: 'OutboxEvent.payload',
    kind: 'json-reference',
    model: 'OutboxEvent',
    column: 'payload',
    nullable: false,
    paths: [],
    note: 'Event snapshot; the worker trusts only the event row’s own tenantId and aggregate.',
  },
  {
    id: 'InternalAuditEvent.beforeData',
    kind: 'json-reference',
    model: 'InternalAuditEvent',
    column: 'beforeData',
    nullable: true,
    paths: [],
    note: 'Audit snapshot.',
  },
  {
    id: 'InternalAuditEvent.afterData',
    kind: 'json-reference',
    model: 'InternalAuditEvent',
    column: 'afterData',
    nullable: true,
    paths: [],
    note: 'Audit snapshot.',
  },
];

const EXTERNAL_IDENTIFIERS: readonly ExternalIdentifier[] = [
  {
    id: 'NotificationDelivery.providerMessageId',
    kind: 'external-identifier',
    model: 'NotificationDelivery',
    column: 'providerMessageId',
    nullable: true,
    system: 'email provider',
  },
];

export const TENANT_RELATIONSHIPS: readonly TenantRelationship[] =
  Object.freeze([
    ...DIRECT_REFERENCES,
    ...POLYMORPHIC_REFERENCES,
    ...JSON_REFERENCES,
    ...EXTERNAL_IDENTIFIERS,
  ]);
